stages:
  - build
  - push

build:
  image: docker
  stage: build
  script:
     - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
     - docker build --pull --no-cache -t "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}" .
     - docker tag "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}" ndamiens/nginx-php:latest
     - docker push "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}"

push:
  image: docker
  only:
     - master
  stage: push
  script:
     - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
     - docker push ndamiens/nginx-php:latest
     - docker logout

