sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      if: branch = master
      script:
      - docker build -t $DOCKER_USERNAME/nginx-php .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/nginx-php
env:
  global:
  - secure: mc+TdfdV2Quuhg35T7DphRUjN60S1t3mmHbMD0YRX3poNpl/3l4J3TRY7cXclxuOissgmghO7X8O9BLQFDr8NIfMOjlJjzcr3DIuWnHoRCFBEG1YyMA40yrbxjilN2xkrUQCNfyxEb+8CwGe1OrJhVLf+f5/q7+fm2HKYGxJa5oERWPU42mlyColuH7Hl9Q1SddGTYgeOpO7L5pS2Av2xwVF0RTgUnCXZAej1+ToQZ9q/Pa722YShQ2/+K8DrnIpoa6pyhLKFBv67rWeV2Uci5K+8Ix/m9wPDf73xZm13hnp8mNkpEL345Am45pcxmdF/bg6HLmEzZwm2EfjPXhPUls3T6Z+RwMwbsVHYj12b/iQ8U0m6H83FLVMWJTdVp55UyIlmSnMZmDeyrtrxfnydV4d7euDrMiz4FsDGXMTXpmx6DcuvHb+FGxlpwuoVY9Fn6hMG6kjXCaKMiLd2CAuQvKRoAfEMVsLXPWWhXTG9NF4LoRFiC3iLiVWmYGCmMTdEVZ4PCwO503f/Gu1Was0GPE7DdtxvWd1tJxIg8L4LAeeSlzf79cJmLcbVj4C2X+yAgFpCkYbCtQ8IC9yeKs5ztkS0JgVVDh12Of1qzcvhAIhl7EGrp4Ou05a2mCpCZNMcKpNi9ITcPacjqdt96WsKXlbB4jiflEa5f0grSnNxdA=
  - secure: p+BIL4uxuUQtSzF1QmkapHwWvcfpg3BwHIWfF7eCpBJTbJxFS4ZgYdDnvN37czKmaN7OiatlYpUhNVvBjI/zBlwPaK2JoNHEwi/luLiNlMx/IgKABwrWplLdq64Ik0WCn+nHOqa9JhrRHQ3cFc/21+xLbfgIB3Hq2fVb01dQwNN59eNx/8cTjzltbrbubpwgSmGmNrL3oV+0C2MPu9OXICgINvhQTxZN4TNr/3jLVWxVTyNg9yizjua6ZjMsnDsXtrbxfHwQV6wlgHCIRsdm2aeOwgXUjq6huY6Yu8//B8WlDglLBa+j+VGvskgx2qz1VpUI6jxXkMf/VbMiEvoHVgXCD7kfwAQHaeIXglmjehhPxHlwC7c1h7lWyTETJIfXc+z4hcJLfVmJN5kVW9cImkeKS9YM7a30T9xBDQ25Mw5Xwdoz8l3WNJ/aGxxlPObvqk4YcFlxlRUm1N6edAEn6vAULeRZRdwAr594/LIPNcYm2i9xv+EdUhr+UZ9Uxau89NwJUoWCqpVbQDV6Gsr44TteIRIAXl2FCbpZJ9NNvFn1RjALw/uxhaldji8iyn+dyKPBz/KoKVxsT53VKgy+QxtrEKVRg4HmW00boRDaArrLUbQTA39hSq12F2hkOfTYDPePt0cJtc+Hs2INciLZwhJlzJ1Q5PY4jal+fz0Its4=
