name: ci

on:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: buster

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Scaleway
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/ndamiens
          username: anyuser
          password: ${{ secrets.SCW_REGISTRY_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rg.fr-par.scw.cloud/ndamiens/nginx:buster
